### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by anouar-hamed** [OverZealous/gulp-task-listing#11]
i think that there's a dependency problem. im having this error:

Error: Cannot find module 'gulp'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object. (/home/anouar/node_modules/Test-gulp-task-listing/gulp-task-listing/index.js:6:12)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)

you can see it on this project after:

> npm install
> gulp

[Test-gulp-task-listing.zip](https://github.com/OverZealous/gulp-task-listing/files/149038/Test-gulp-task-listing.zip)

**Comment by OverZealous** [comment]
I already explained this in the other bug you commented on.   There is no bug, plenty of people are using this library without issue.  You have to add gulp to your project yourself.

**Comment by anouar-hamed** [comment]
did you at least tried the attached project? gulp is already in my package.json.

**Comment by OverZealous** [comment]
Did you take the time to reduce the issue to a minimal, reproducible case? You can't really expect me to download and run some random zip file for a free, open source project.

I don't have time to provide free support, and the library works fine for me and many others.  The issue is in your setup.  You are free to fork the library.

**Comment by anouar-hamed** [comment]
Yes, i did take the time to reduce to minimal reproductible case, as i explained in my first comment. And THAT zip contains that case.

So if you're not curious about this issue or you don't have the time to investigate it, im sorry to bother you.
