### ISSUE TITLE
Gulp 4 support

### ISSUE THREAD

**Issue by pcabello** [OverZealous/gulp-task-listing#12]
Hi,

I'm having problem after I updated the gulp for 4, it have started displayed an error "TypeError: Cannot convert undefined or null to object", so I would like to know if it should continue working with gulp 4 too ?if so, what do I need to do to work again?

**Comment by OverZealous** [comment]
Sorry, I have no intention of upgrading this to work with Gulp 4 at this time.

**Comment by Rabadash8820** [comment]
@OverZealous I just ran into this issue after updating as well.  With a plugin this simple, why do you not intend to upgrade?
