### ISSUE TITLE
Not working with multiple gulp files

### ISSUE THREAD

**Issue by MCKRUZ** [OverZealous/gulp-task-listing#9]
Given this file structure

https://github.com/martinmicunda/employee-scheduling-ui

with the tasks being segregated under different files.  (see the gulp file)

gulp-task-listing produces nothing.

**Comment by OverZealous** [comment]
I'm seriously in no way going to go through that entire project.  If you want some help, please narrow this down to a minimal test case.

Plus, the library is only a handful of lines long, it should be pretty easy to figure out what's going on.  All it does is loop over the tasks within gulp, filter out some of them, and render it.

**Comment by MCKRUZ** [comment]
Sure...sorry here is it more narrowly

Initial gulpfile (https://github.com/martinmicunda/employee-scheduling-ui/blob/master/gulpfile.js) has this line

require('require-dir')('./gulp/tasks', { recurse: true });

Which basically takes everything in the gulp/tasks folder and includes them so that they are all accessible to gulp.

then we have one file...say...html (https://github.com/martinmicunda/employee-scheduling-ui/blob/master/gulp/tasks/html.js)

that has this task

gulp.task('htmlhint', () => {
    return gulp.src([path.app.html, path.app.templates])
        .pipe(htmlhint('.htmlhintrc'))
        .pipe(htmlhint.reporter())
        .pipe(htmlhint.failReporter());
});

I should be able to create another file...say called...general and include this code
/**
 * Return all of the available tasks
 *
 * @return {Void}
 */
gulp.task('help', () => {
    taskListing;
});

Then be able to run "gulp help" from my command line and see the HTMLHINT task.  But I can't.  Make sense?

**Comment by OverZealous** [comment]
Honestly, I'm not sure there's anything I can do.  This is literally the only significant line in the entire script:

```js
var tasks = Object.keys(gulp.tasks).sort();
```

Put that in your own task and see what you get.  I don't really think it's an issue with `gulp-task-listing`.

**Comment by OverZealous** [comment]
I haven't heard back from this for a while.  You can re-open if you want.
